export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_SINGLE_COMMENT = 'FETCH_SINGLE_COMMENT';

export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';